name: hqtool
description: AI SRT TOOL
version: 1.0.0
homepage: https://www.youtube.com/@hq_net
repository: https://github.com/ruwiss/hqtool

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dio: ^5.7.0
  google_generative_ai: ^0.4.6
  interact: ^2.2.0
  intl: ^0.18.1
  path: ^1.9.1
  xml2json: ^6.2.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

platforms:
  windows:
